import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import "../globals.css";
import Navbar from "../../components/layout/NavbarLayout";
import Footer from "@/src/components/layout/Footer";
import { Providers } from "@/src/utils/Provider";
import BookingModal from "@/src/components/ui/Modal";
import { Suspense } from "react";
import Loading from "../loading";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className="antialiased">
        <NextIntlClientProvider messages={messages}>
          <Providers>
            <Navbar /> {/* Navbar doimiy turadi */}
            <main className={`${geistSans.variable} ${geistMono.variable} font-sans`}>
              {children} {/* Sahifa mazmuni shu yerga tushadi */}
              <Footer />
              <BookingModal />
            </main>
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}